version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_USER: user1 # Non-root username
      MYSQL_PASSWORD: pass1 # Non-root user password
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://user1:pass1@db:3306/test" # Use the service name 'db'
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
